baseURL = "http://copters.io"
disqusShortname = "username"
languageCode = "en-us"
theme = "minimal"
title = "Interested in copters.io?"
[[menu.icon]]
name = "envelope-o"
url = "mailto:james.ohalloran@mightypebble.com"
weight = 1
[[menu.icon2]]
name = "envelope-o"
url = "mailto:james.ohalloran@mightypebble.com"
weight = 1
[params]
accent = "red"
author = "Calin Tataru"
backgroundcolor = "black"
css = ["/css/project.css"]
description = "Contact <a href='mailto:james.ohalloran@mightypebble.com'>james.ohalloran@mightypebble.com!</a> with your best offer"
font = "Raleway"
githubusername = "#"
highlight = true
highlightlanguages = ["go", "haskell", "kotlin", "scala", "swift"]
highlightstyle = "solarized-dark"
showborder = true
