---
new_page_extension: md
auto_deploy: true
admin_path: "/admin"
webhook_url: 
sections:
  posts:
    default_front_matter_template: post
upload_dir: ''
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.26'
