---
upload_path: "/"
frontmatter_file_url_template: "/uploads/:year:/:month:/:day:"
body_file_url_template: "/uploads/:year:/:month:/:day:"
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
  posts:
    default_front_matter_template: post
version: '0.26'
