---
pages:
- posts/test-page.md
- posts/test-post-1.md
hide_body: false
is_partial: false
fields:
- type: textarea
  default: blah
  label: '123'
  name: '123'
  config:
    wysiwyg: true
    schema:
      format: markdown
      flavour: CommonMark
- type: datetime
  name: my_date
  label: my date
